cargo-features = ["panic-immediate-abort"]

[package]
name = "fasthash"
version = "0.1.0"
edition = "2024"

[dependencies]
argh = { version = "0.1.19", default-features = false, features = ["help"] }
crossfire = "3.1.16"
digest = { version = "0.11.3", features = ["alloc"] }
hex-simd = "0.8.0"
parse-size = "1.1.0"
sha2 = { version = "0.11.0", default-features = false }
sha3 = { version = "0.12.0", default-features = false }

[target.'cfg(all(unix, not(target_os = "macos")))'.dependencies]
rustix = { version = "1.1.4", default-features = false, features = [
    "fs",
    "std",
] }

[profile.release]
lto = true
strip = true
panic = "immediate-abort"
opt-level = 3
codegen-units = 1
split-debuginfo = "packed"
debug = "full"
