name: nightly-release

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.runner }}

    strategy:
      fail-fast: false

      matrix:
        include:
          # Linux musl ARM64
          - artifact: fasthash-linux-musl-arm64
            runner: ubuntu-24.04
            target: aarch64-unknown-linux-musl

          # Linux glibc 2.31 x64
          - artifact: fasthash-linux-glibc-x86_64
            runner: ubuntu-24.04
            target: x86_64-unknown-linux-gnu
            zig_target: x86_64-linux-gnu.2.31

          # Linux musl x64
          - artifact: fasthash-linux-musl-x86_64
            runner: ubuntu-24.04
            target: x86_64-unknown-linux-musl

          # Windows x64
          - artifact: fasthash-windows-x86_64.exe
            runner: windows-2022
            target: x86_64-pc-windows-msvc

          # Windows ARM64
          - artifact: fasthash-windows-arm64.exe
            runner: windows-2022
            target: aarch64-pc-windows-msvc

          # macOS ARM64
          - artifact: fasthash-macos-arm64
            runner: macos-15
            target: aarch64-apple-darwin

          # Android ARM64
          - artifact: fasthash-android-arm64
            runner: ubuntu-24.04
            target: aarch64-linux-android

    name: ${{ matrix.artifact }}

    steps:
      - uses: actions/checkout@v6

      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: ${{ matrix.target }}
          components: rust-src

      - uses: Swatinem/rust-cache@v2

      - name: Install zig
        if: matrix.zig_target != ''
        uses: mlugg/setup-zig@v2

      # zig only for glibc baseline
      - name: Install zigbuild
        if: matrix.zig_target != ''
        run: cargo install cargo-zigbuild

      # musl linker
      - name: Install musl tools
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: Install cargo-ndk
        if: matrix.target == 'aarch64-linux-android'
        run: cargo install cargo-ndk

      # rust-lld linker
      - name: Configure rust-lld linker
        if: matrix.target == 'aarch64-pc-windows-msvc' ||
          matrix.target == 'aarch64-unknown-linux-musl'
        shell: bash
        run: |
          mkdir -p .cargo

          cat >> .cargo/config.toml <<EOF
          [target.${{ matrix.target }}]
          linker = "rust-lld"
          EOF

      # GNU Linux with glibc baseline
      - name: Build GNU Linux
        if: matrix.zig_target != ''
        env:
          CARGO_ZIGBUILD_TARGET: ${{ matrix.zig_target }}
        run: |
          cargo zigbuild \
            --release \
            --target ${{ matrix.target }}

      # Android
      - name: Build Android
        if: matrix.target == 'aarch64-linux-android'
        run: |
          cargo ndk \
            --target aarch64-linux-android \
            build \
            --release

      # Everything else
      - name: Build
        if: |
          matrix.zig_target == '' &&
          matrix.target != 'aarch64-linux-android'
        shell: bash
        run: |
          cargo build \
            --release \
            --target ${{ matrix.target }}

      - name: Collect
        shell: bash
        run: |
          mkdir dist

          BIN=fasthash
          case "${{ matrix.target }}" in
            *windows*)
              BIN="${BIN}.exe"
              ;;
          esac

          cp \
            "target/${{ matrix.target }}/release/${BIN}" \
            "dist/${{ matrix.artifact }}"

      - uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.artifact }}
          path: dist/*

  release:
    needs:
      - build

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/download-artifact@v8
        with:
          path: artifacts

      - id: date
        run: |
          echo "date=$(date -u +%Y%m%d-%H%M%S)" >> $GITHUB_OUTPUT

      - uses: softprops/action-gh-release@v3
        with:
          tag_name: nightly
          name: Nightly ${{ steps.date.outputs.date }}
          prerelease: true
          files: artifacts/**/*
          overwrite_files: true
